#!/usr/bin/env python3

import os
import argparse

parser = argparse.ArgumentParser(description='Generate a brand new password.')
parser.add_argument('-l', '--length', metavar='LEN', type=int, default=32,
                    help='length of your password')
parser.add_argument('-n', '--count', metavar='N', type=int, default=1,
                    help='ammount of passwords to generate')
parser.add_argument('-r', '--random', action='store_true',
                    help='use /dev/random as source of randomity')
args = parser.parse_args()

if args.random:
    try:
        dev_random = open('/dev/random', 'rb')
    except IOError:
        dev_random = None


def random_byte():
    if args.random and dev_random:
            return dev_random.read(1)
    else:
        return os.urandom(1)


def randchar(fr=32, to=127):
    if fr > to:
        fr, to = to, fr
    return chr(ord(random_byte()) % (to - fr) + fr)


for _ in range(args.count):
    print("".join(randchar(33, 127) for _ in range(args.length)))
